# 라이브러리

In [1]:
import pandas as pd
import numpy as np
from scipy. stats import mode

# 데이터 불러오기

In [2]:
def csvread(data):
    return pd.read_csv(data)

In [3]:
data1=csvread('base_data1.csv')
data2=csvread('base_data2.csv')
data3=csvread('base_data3.csv')

In [4]:
data1.head()

T_ID T_DATA_CLASS  T_EDATE  T_SEX  T_AGE  T_INCOME  T_MARRY
0  K_BASE_00001          B20   200802      2     42     99999    99999
1  K_BASE_00002          B20   200306      2     58         1        2
2  K_BASE_00003          B14   201108      2     60     99999        2
3  K_BASE_00004          B29   201004      2     73         1        5
4  K_BASE_00005          B23   200410      2     59         2        2

In [5]:
data2.head()

T_ID T_DATA_CLASS  T_HTN  T_HTNAG  T_DM  T_DMAG  T_LIP  T_LIPAG  \
0  K_BASE_00001          B20      1    77777     1   77777      2       42   
1  K_BASE_00002          B20      2       50     1   77777      1    77777   
2  K_BASE_00003          B14      2       50     1   77777      2       50   
3  K_BASE_00004          B29      2       63     1   77777      1    77777   
4  K_BASE_00005          B23      1    77777     1   77777      1    77777   

   T_FMFHT1  T_FMFHT2  ...  T_SMDUMO   T_SMAM  T_PACKYR  T_PSM  T_EXER  \
0         2         2  ...     66666  77777.0   77777.0      1       2   
1         1         1  ...     66666  77777.0   77777.0      2       1   
2         1         1  ...     77777  77777.0   77777.0      1       2   
3         1         1  ...     77777  77777.0   77777.0      1       2   
4         1         1  ...     77777  77777.0   77777.0      1       1   

   T_MNSAG  T_PMYN  T_PMAG  T_PREG  T_FPREGAG  
0    99999       1   77777       2         22  
1       16       2      55       2         18  
2       14       2      47       2         27  
3       16       2      54       2         21  
4       14       2      50       2         24  

[5 rows x 39 columns]

In [6]:
data3.head()

T_ID T_DATA_CLASS  T_SBP  T_DBP  T_PULSE  T_WAIST  T_HIP  T_HEIGHT  \
0  K_BASE_00001          B20    115     78       74       82     95       164   
1  K_BASE_00002          B20    143     87       66       89     99       156   
2  K_BASE_00003          B14    120     80       62       78     90       154   
3  K_BASE_00004          B29    104     62       74       86     93       143   
4  K_BASE_00005          B23    125     81       70       86     98       150   

   T_WEIGHT  T_BMI  T_HBA1C  T_GLU0  T_CREATINE  T_AST  T_ALT  T_TCHL  T_HDL  \
0        64     24  66666.0      68        0.60     20     12     172     62   
1        64     26  66666.0      86        0.60     17     13     197     62   
2        54     23  66666.0      86        0.80     39     53     156     46   
3        55     27  66666.0     108        0.76     16     28     170     39   
4        60     27  66666.0      91        0.68     18     13     178     65   

   T_LDL  T_TG  
0    102    38  
1    119    79  
2     88   112  
3    109   109  
4    103    52

## 데이터 합치기

In [7]:
data2=data2.drop(['T_ID','T_DATA_CLASS'],axis=1)
data3=data3.drop(['T_ID','T_DATA_CLASS'],axis=1)

In [8]:
data2.head()

T_HTN  T_HTNAG  T_DM  T_DMAG  T_LIP  T_LIPAG  T_FMFHT1  T_FMFHT2  T_FMFDM1  \
0      1    77777     1   77777      2       42         2         2         1   
1      2       50     1   77777      1    77777         1         1         1   
2      2       50     1   77777      2       50         1         1         2   
3      2       63     1   77777      1    77777         1         1         1   
4      1    77777     1   77777      1    77777         1         1         1   

   T_FMFDM2  ...  T_SMDUMO   T_SMAM  T_PACKYR  T_PSM  T_EXER  T_MNSAG  T_PMYN  \
0         1  ...     66666  77777.0   77777.0      1       2    99999       1   
1         1  ...     66666  77777.0   77777.0      2       1       16       2   
2         1  ...     77777  77777.0   77777.0      1       2       14       2   
3         1  ...     77777  77777.0   77777.0      1       2       16       2   
4         1  ...     77777  77777.0   77777.0      1       1       14       2   

   T_PMAG  T_PREG  T_FPREGAG  
0   77777       2         22  
1      55       2         18  
2      47       2         27  
3      54       2         21  
4      50       2         24  

[5 rows x 37 columns]

In [9]:
data3.head()

T_SBP  T_DBP  T_PULSE  T_WAIST  T_HIP  T_HEIGHT  T_WEIGHT  T_BMI  T_HBA1C  \
0    115     78       74       82     95       164        64     24  66666.0   
1    143     87       66       89     99       156        64     26  66666.0   
2    120     80       62       78     90       154        54     23  66666.0   
3    104     62       74       86     93       143        55     27  66666.0   
4    125     81       70       86     98       150        60     27  66666.0   

   T_GLU0  T_CREATINE  T_AST  T_ALT  T_TCHL  T_HDL  T_LDL  T_TG  
0      68        0.60     20     12     172     62    102    38  
1      86        0.60     17     13     197     62    119    79  
2      86        0.80     39     53     156     46     88   112  
3     108        0.76     16     28     170     39    109   109  
4      91        0.68     18     13     178     65    103    52

In [10]:
data=pd.concat([data1,data2,data3],axis=1)
data

T_ID T_DATA_CLASS  T_EDATE  T_SEX  T_AGE  T_INCOME  T_MARRY  \
0     K_BASE_00001          B20   200802      2     42     99999    99999   
1     K_BASE_00002          B20   200306      2     58         1        2   
2     K_BASE_00003          B14   201108      2     60     99999        2   
3     K_BASE_00004          B29   201004      2     73         1        5   
4     K_BASE_00005          B23   200410      2     59         2        2   
...            ...          ...      ...    ...    ...       ...      ...   
9995  K_BASE_09996          B20   201003      1     66         3        2   
9996  K_BASE_09997          B20   200510      1     58         7        2   
9997  K_BASE_09998          B14   201107      1     57         5        2   
9998  K_BASE_09999          B13   201108      2     43         7        2   
9999  K_BASE_10000          B11   201309      2     43         8        2   

      T_HTN  T_HTNAG  T_DM  ...  T_BMI  T_HBA1C  T_GLU0  T_CREATINE  T_AST  \
0         1    77777     1  ...     24  66666.0      68        0.60     20   
1         2       50     1  ...     26  66666.0      86        0.60     17   
2         2       50     1  ...     23  66666.0      86        0.80     39   
3         2       63     1  ...     27  66666.0     108        0.76     16   
4         1    77777     1  ...     27  66666.0      91        0.68     18   
...     ...      ...   ...  ...    ...      ...     ...         ...    ...   
9995      1    77777     1  ...     23  66666.0      93        0.90     25   
9996      2       58     2  ...     25  66666.0     120        0.70     19   
9997      1    77777     1  ...     23  66666.0      86        1.40     22   
9998      1    77777     1  ...     24  66666.0     104        0.80     37   
9999      1    77777     1  ...     28  66666.0      69        0.60     19   

      T_ALT  T_TCHL  T_HDL  T_LDL  T_TG  
0        12     172     62    102    38  
1        13     197     62    119    79  
2        53     156     46     88   112  
3        28     170     39    109   109  
4        13     178     65    103    52  
...     ...     ...    ...    ...   ...  
9995     25     149     53     85    53  
9996     16     159     39    101    93  
9997     28     188     34     76   389  
9998     46     200     63    126    54  
9999     17     205     38    139   142  

[10000 rows x 61 columns]

## 컬럼명 변경

In [11]:
data.columns

Index(['T_ID', 'T_DATA_CLASS', 'T_EDATE', 'T_SEX', 'T_AGE', 'T_INCOME',
       'T_MARRY', 'T_HTN', 'T_HTNAG', 'T_DM', 'T_DMAG', 'T_LIP', 'T_LIPAG',
       'T_FMFHT1', 'T_FMFHT2', 'T_FMFDM1', 'T_FMFDM2', 'T_DRINK', 'T_DRDU',
       'T_TAKFQ', 'T_TAKAM', 'T_RICEFQ', 'T_RICEAM', 'T_WINEFQ', 'T_WINEAM',
       'T_SOJUFQ', 'T_SOJUAM', 'T_BEERFQ', 'T_BEERAM', 'T_HLIQFQ', 'T_HLIQAM',
       'T_TOTALC', 'T_SMOKE', 'T_SMDUYR', 'T_SMDUMO', 'T_SMAM', 'T_PACKYR',
       'T_PSM', 'T_EXER', 'T_MNSAG', 'T_PMYN', 'T_PMAG', 'T_PREG', 'T_FPREGAG',
       'T_SBP', 'T_DBP', 'T_PULSE', 'T_WAIST', 'T_HIP', 'T_HEIGHT', 'T_WEIGHT',
       'T_BMI', 'T_HBA1C', 'T_GLU0', 'T_CREATINE', 'T_AST', 'T_ALT', 'T_TCHL',
       'T_HDL', 'T_LDL', 'T_TG'],
      dtype='object')

In [12]:
new_col=['대상자ID','단위데이터','조사일자','성별','만나이','월평균수입','현재결혼상태',
         '고혈압진단여부','고혈압진단나이','당뇨병진단여부','당뇨병진단나이','고지혈증진단여부','고지혈증진단나이',
         '아버지고혈압진단여부','어머니고혈압진단여부','아버지당뇨병진단여부','어머니당뇨병진단여부',
         '음주여부','총음주기간',
         '막걸리지난1년평균섭취횟수','막걸리1회음주량(잔)','정종지난1년평균섭취횟수','정종1회음주량(잔)','와인지난1년평균섭취횟수','와인1회음주량(잔)',
         '소주지난1년평균섭취횟수','소주1회음주량(잔)','맥주지난1년평균섭취횟수','맥주1회음주량(잔)','양주지난1년평균섭취횟수','양주1회음주량(잔)','총음주량',
         '흡연여부','총흡연기간(년)','총흡연기간(달)','하루흡연량(개비)','연흡연량(갑)','간접흡연여부',
         '규칙적운동여부(몸에땀이날정도)','초경만나이','폐경여부','폐경만나이','임신경험여부','첫임신시만나이',
         '수축기혈압평균(mmHg)','이완기혈압평균(mmHg)','맥박수(회/분)',
         '허리둘레(cm)','엉덩이둘레(cm)','신장(cm)','체중(kg)','BMI(kg/m^2)',
         '혈액_HbA1C(%)','혈액_Glucose(mg/dL)','혈액_Creatinine(mg/dL)','혈액_Ast(IU/L)','혈액_Alt(IU/L)',
         '혈액_Total-cholesterol(mg/dL)','혈액_Hdl-cholestrol(mg/dL)','혈액_LDL-cholestrol(mg/dL)','혈액_Triglyceride(mg/dL)']

In [13]:
data.columns=new_col
data.head()

대상자ID 단위데이터    조사일자  성별  만나이  월평균수입  현재결혼상태  고혈압진단여부  고혈압진단나이  \
0  K_BASE_00001   B20  200802   2   42  99999   99999        1    77777   
1  K_BASE_00002   B20  200306   2   58      1       2        2       50   
2  K_BASE_00003   B14  201108   2   60  99999       2        2       50   
3  K_BASE_00004   B29  201004   2   73      1       5        2       63   
4  K_BASE_00005   B23  200410   2   59      2       2        1    77777   

   당뇨병진단여부  ...  BMI(kg/m^2)  혈액_HbA1C(%)  혈액_Glucose(mg/dL)  \
0        1  ...           24      66666.0                 68   
1        1  ...           26      66666.0                 86   
2        1  ...           23      66666.0                 86   
3        1  ...           27      66666.0                108   
4        1  ...           27      66666.0                 91   

   혈액_Creatinine(mg/dL)  혈액_Ast(IU/L)  혈액_Alt(IU/L)  \
0                  0.60            20            12   
1                  0.60            17            13   
2                  0.80            39            53   
3                  0.76            16            28   
4                  0.68            18            13   

   혈액_Total-cholesterol(mg/dL)  혈액_Hdl-cholestrol(mg/dL)  \
0                          172                        62   
1                          197                        62   
2                          156                        46   
3                          170                        39   
4                          178                        65   

   혈액_LDL-cholestrol(mg/dL)  혈액_Triglyceride(mg/dL)  
0                       102                      38  
1                       119                      79  
2                        88                     112  
3                       109                     109  
4                       103                      52  

[5 rows x 61 columns]

## 일부 컬럼 삭제

In [14]:
# 머신러닝에 필요없는 값
data=data.drop(['단위데이터','조사일자'],axis=1)

# 해당 수치가 높으면 당뇨 판정. 과적합요인
data=data.drop(['혈액_HbA1C(%)','혈액_Glucose(mg/dL)','혈액_Creatinine(mg/dL)','혈액_Ast(IU/L)','혈액_Alt(IU/L)','혈액_Total-cholesterol(mg/dL)','혈액_Hdl-cholestrol(mg/dL)','혈액_LDL-cholestrol(mg/dL)','혈액_Triglyceride(mg/dL)'],axis=1)

# 해당 수치가 높으면 고혈압 판정. 과적합요인
data=data.drop(['수축기혈압평균(mmHg)','이완기혈압평균(mmHg)','맥박수(회/분)'],axis=1)

# 지나치게 자세한 음주 수치 삭제
data=data.drop(['막걸리지난1년평균섭취횟수','막걸리1회음주량(잔)','정종지난1년평균섭취횟수','정종1회음주량(잔)','와인지난1년평균섭취횟수','와인1회음주량(잔)',
         '소주지난1년평균섭취횟수','소주1회음주량(잔)','맥주지난1년평균섭취횟수','맥주1회음주량(잔)','양주지난1년평균섭취횟수','양주1회음주량(잔)','총음주량'],axis=1)

# 중복된 흡연 데이터 삭제
data=data.drop(['총흡연기간(달)','연흡연량(갑)'],axis=1)

In [15]:
data.columns

Index(['대상자ID', '성별', '만나이', '월평균수입', '현재결혼상태', '고혈압진단여부', '고혈압진단나이',
       '당뇨병진단여부', '당뇨병진단나이', '고지혈증진단여부', '고지혈증진단나이', '아버지고혈압진단여부',
       '어머니고혈압진단여부', '아버지당뇨병진단여부', '어머니당뇨병진단여부', '음주여부', '총음주기간', '흡연여부',
       '총흡연기간(년)', '하루흡연량(개비)', '간접흡연여부', '규칙적운동여부(몸에땀이날정도)', '초경만나이', '폐경여부',
       '폐경만나이', '임신경험여부', '첫임신시만나이', '허리둘레(cm)', '엉덩이둘레(cm)', '신장(cm)',
       '체중(kg)', 'BMI(kg/m^2)'],
      dtype='object')

# 결측치

## 결측치 조회
66666=조사안함,77777=해당없음,99999=미상/무응답/미측정

In [16]:
# 결측치(val)가 포함된 열 찾는 함수
def nandata(data,val):
    col=[]
    for x in data.columns:
        if data[data[x]==val][x].count() > 0:
            col.append(x)
    print(f'{val}을 포함하는 열의 개수 {len(col)}')
    return col

In [17]:
# 특정 컬럼의 결측치 확인
def nandf2(data,col):
    nanlist=pd.DataFrame()
    nannum=['66666','77777','99999']
    nanlist['결측값']=nannum
    nanlist=nanlist.set_index(keys='결측값')

    for x in data[col]:
        col=[]
        col.append(data[data[x]==66666][x].count())
        col.append(data[data[x]==77777][x].count())
        col.append(data[data[x]==99999][x].count())
        if sum(col) > 0:
            nanlist[x]=col
    print(nanlist.columns)
    return nanlist

#nanlist=nandf(data)
#nanlist


In [18]:
# 특정 컬럼의 결측치 확인
def nandf3(data,col):
    nanlist=pd.DataFrame()
    nannum=['66666','77777','99999']
    nanlist['결측값']=nannum
    nanlist=nanlist.set_index(keys='결측값')

    for x in data[col]:
        col=[]
        #col.append(data[data[x]==66666][x].count())
        #col.append(data[data[x]==77777][x].count())
        col.append(data[data[x]==99999][x].count())
        if sum(col) > 0:
            nanlist[x]=col
    print(nanlist.columns)
    return nanlist

#nanlist=nandf(data)
#nanlist


In [19]:
val6=nandata(data,66666)
val7=nandata(data,77777)
val9=nandata(data,99999)

66666을 포함하는 열의 개수 1
77777을 포함하는 열의 개수 11
99999을 포함하는 열의 개수 25


In [20]:
def nandf(data):
    nanlist=pd.DataFrame()
    nannum=['66666','77777','99999']
    nanlist['결측값']=nannum
    nanlist=nanlist.set_index(keys='결측값')

    for x in data.columns:
        col=[]
        col.append(data[data[x]==66666][x].count())
        col.append(data[data[x]==77777][x].count())
        col.append(data[data[x]==99999][x].count())
        if sum(col) > 0:
            nanlist[x]=col
    print(nanlist.columns)
    return nanlist

#nanlist=nandf(data)
#nanlist


In [21]:
nanlist=nandf(data)
nanlist

Index(['월평균수입', '현재결혼상태', '고혈압진단여부', '고혈압진단나이', '당뇨병진단여부', '당뇨병진단나이',
       '고지혈증진단여부', '고지혈증진단나이', '음주여부', '총음주기간', '흡연여부', '총흡연기간(년)',
       '하루흡연량(개비)', '간접흡연여부', '규칙적운동여부(몸에땀이날정도)', '초경만나이', '폐경여부', '폐경만나이',
       '임신경험여부', '첫임신시만나이', '허리둘레(cm)', '엉덩이둘레(cm)', '신장(cm)', '체중(kg)',
       'BMI(kg/m^2)'],
      dtype='object')


월평균수입  현재결혼상태  고혈압진단여부  고혈압진단나이  당뇨병진단여부  당뇨병진단나이  고지혈증진단여부  고지혈증진단나이  \
결측값                                                                            
66666    873       0        0        0        0        0         0         0   
77777      0       0        0     7977        0     9269         0      9186   
99999   1139      70       18       88       19       44        22        67   

       음주여부  총음주기간  ...  초경만나이  폐경여부  폐경만나이  임신경험여부  첫임신시만나이  허리둘레(cm)  \
결측값                 ...                                                  
66666     0      0  ...      0     0      0       0        0         0   
77777     0   5017  ...   3460  3460   5967    3460     3657         0   
99999    61    340  ...    244    77    323      31      103       132   

       엉덩이둘레(cm)  신장(cm)  체중(kg)  BMI(kg/m^2)  
결측값                                            
66666          0       0       0            0  
77777          0       0       0            0  
99999        139      46      47           51  

[3 rows x 25 columns]

## 결측치처리 계획
66666(조사안함), 99999(미상/무응답/미측정) => 데이터 처리 
77777(해당없음) => 유지

1. 수입 결혼상태
'월평균수입' = 최빈값  
'현재결혼상태' = 최빈값  

2. 병 진단
'고혈압진단여부' = 최빈값  
'고혈압진단나이' = 평균값  
'당뇨병진단여부' = 최빈값  
'당뇨병진단나이' = 평균값  
'고지혈증진단여부' = 최빈값  
'고지혈증진단나이'= 평균값  

3. 음주
'음주여부' = 최빈값
'총음주기간'
'막걸리지난1년평균섭취횟수', 
'막걸리1회음주량(잔)',
'정종지난1년평균섭취횟수', 
'정종1회음주량(잔)', 
'와인지난1년평균섭취횟수', 
'와인1회음주량(잔)',
'소주지난1년평균섭취횟수', 
'소주1회음주량(잔)', 
'맥주지난1년평균섭취횟수', 
'맥주1회음주량(잔)',
'양주지난1년평균섭취횟수', 
'양주1회음주량(잔)', 

4. 흡연
'흡연여부', 
'총흡연기간(년)', 
'총흡연기간(달)',
'하루흡연량(개비)', 
'연흡연량(갑)', 
'간접흡연여부', 

5. 운동
'규칙적운동여부(몸에땀이날정도)', 

6. 임신
'초경만나이', 
'폐경여부',
'폐경만나이', 
'임신경험여부', 
'첫임신시만나이', 

7. 신체정보
'허리둘레(cm)', 
'엉덩이둘레(cm)', 
'신장(cm)', 
'체중(kg)', 
'BMI(kg/m^2)',

In [22]:
# 결측치(66666,99999)를 평균값(0) 또는 최빈값(1)으로 대체하는 함수
def nanchange(col,am):
    nan_index=data[(data[col]==99999) | (data[col]==66666)].index
    
    if am == 0:
        x=round(np.mean(data[col].drop(nan_index)))
        data[col]=data[col].replace(99999,x)
        data[col]=data[col].replace(66666,x)
        print(f'{col} 결측치 대체 평균값(반올림) :',x)
    elif am == 1:
        x=int(mode(data[col].drop(nan_index))[0])
        data[col]=data[col].replace(99999,x)
        data[col]=data[col].replace(66666,x)
        print(f'{col} 결측치 대체 최빈값 :',x)
    else :
        print('평균값을 원하면 am=0, 최빈값을 원하면 am=1 입력해주세요')
        
    return data

In [23]:
# 결측치(66666,99999)를 평균값(0) 또는 최빈값(1)으로 대체하는 함수 / 7777도 제외
def nanchange2(col,am):
    nan_index=data[(data[col]==99999) | (data[col]==66666) | (data[col]==77777)].index
    
    if am == 0:
        x=round(np.mean(data[col].drop(nan_index)))
        data[col]=data[col].replace(99999,x)
        data[col]=data[col].replace(66666,x)
        print(f'{col} 결측치 대체 평균값(반올림) :',x)
    elif am == 1:
        x=int(mode(data[col].drop(nan_index))[0])
        data[col]=data[col].replace(99999,x)
        data[col]=data[col].replace(66666,x)
        print(f'{col} 결측치 대체 최빈값 :',x)
    else :
        print('평균값을 원하면 am=0, 최빈값을 원하면 am=1 입력해주세요')
        
    return data
    
    

In [24]:
# 결측치(66666,99999)를 평균값(0) 또는 최빈값(1)으로 대체하는 함수 / 99999만
def nanchange3(col,am):
    nan_index=data[(data[col]==99999)].index
    
    if am == 0:
        x=round(np.mean(data[col].drop(nan_index)))
        data[col]=data[col].replace(99999,x)
        data[col]=data[col].replace(66666,x)
        print(f'{col} 결측치 대체 평균값(반올림) :',x)
    elif am == 1:
        x=int(mode(data[col].drop(nan_index))[0])
        data[col]=data[col].replace(99999,x)
        data[col]=data[col].replace(66666,x)
        print(f'{col} 결측치 대체 최빈값 :',x)
    else :
        print('평균값을 원하면 am=0, 최빈값을 원하면 am=1 입력해주세요')
        
    return data
    
    

In [25]:
# 결측치(66666,99999)를 평균값(0) 또는 최빈값(1)으로 대체하는 함수 / 평균 반올림x
def nanchange4(col,am):
    nan_index=data[(data[col]==99999) | (data[col]==66666)].index
    
    if am == 0:
        x=round(np.median(data[col].drop(nan_index)),1)
        data[col]=data[col].replace(99999,x)
        data[col]=data[col].replace(66666,x)
        print(f'{col} 결측치 대체 평균값(소수점첫째) :',x)
    elif am == 1:
        x=int(mode(data[col].drop(nan_index))[0])
        data[col]=data[col].replace(99999,x)
        data[col]=data[col].replace(66666,x)
        print(f'{col} 결측치 대체 최빈값 :',x)
    else :
        print('평균값을 원하면 am=0, 최빈값을 원하면 am=1 입력해주세요')
        
    return data

## 결측치 처리 진행

### 수입, 결혼상태 결측치

In [26]:
data['월평균수입'].value_counts()

5        1716
6        1472
7        1152
99999    1139
4         897
66666     873
3         804
1         729
2         632
8         586
Name: 월평균수입, dtype: int64

In [27]:
data=nanchange('월평균수입',0)

월평균수입 결측치 대체 평균값(반올림) : 5


In [28]:
data['현재결혼상태'].value_counts()

2        8672
5         665
4         237
1         204
6          80
3          72
99999      70
Name: 현재결혼상태, dtype: int64

In [29]:
data=nanchange('현재결혼상태',1)

현재결혼상태 결측치 대체 최빈값 : 2


### 진단 결측치

In [30]:
def sick_check(col_sick,col_age):
    data=nanchange(col_sick,1)
    index1=data[data[col_sick]==1][col_age].index
    for x in index1:
        data[col_age][x]=77777
        
    index2=data[(data[col_age]==99999) | (data[col_age]==66666) | (data[col_age]==77777)].index
    x=round(np.mean(data[col_age].drop(index2)))
    data[col_age]=data[col_age].replace(99999,x)
    data[col_age]=data[col_age].replace(66666,x)
    print(f'{col_age} 결측치 대체 평균값(반올림) :',x)
    
    return data

In [31]:
data=sick_check('고혈압진단여부','고혈압진단나이')
data=sick_check('당뇨병진단여부','당뇨병진단나이')
data=sick_check('고지혈증진단여부','고지혈증진단나이')

고혈압진단여부 결측치 대체 최빈값 : 1


/var/folders/3r/4hbcmng97wzgph0qydqtq4d00000gn/T/ipykernel_7487/1344407087.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[col_age][x]=77777


고혈압진단나이 결측치 대체 평균값(반올림) : 53
당뇨병진단여부 결측치 대체 최빈값 : 1
당뇨병진단나이 결측치 대체 평균값(반올림) : 52
고지혈증진단여부 결측치 대체 최빈값 : 1
고지혈증진단나이 결측치 대체 평균값(반올림) : 53


In [32]:
nanlist=nandf(data)
nanlist

Index(['고혈압진단나이', '당뇨병진단나이', '고지혈증진단나이', '음주여부', '총음주기간', '흡연여부', '총흡연기간(년)',
       '하루흡연량(개비)', '간접흡연여부', '규칙적운동여부(몸에땀이날정도)', '초경만나이', '폐경여부', '폐경만나이',
       '임신경험여부', '첫임신시만나이', '허리둘레(cm)', '엉덩이둘레(cm)', '신장(cm)', '체중(kg)',
       'BMI(kg/m^2)'],
      dtype='object')


고혈압진단나이  당뇨병진단나이  고지혈증진단나이  음주여부  총음주기간  흡연여부  총흡연기간(년)  하루흡연량(개비)  \
결측값                                                                         
66666        0        0         0     0      0     0         0          0   
77777     7995     9288      9208     0   5017     0      7207       7207   
99999        0        0         0    61    340    68       196        176   

       간접흡연여부  규칙적운동여부(몸에땀이날정도)  초경만나이  폐경여부  폐경만나이  임신경험여부  첫임신시만나이  \
결측값                                                                    
66666       0                 0      0     0      0       0        0   
77777       0                 0   3460  3460   5967    3460     3657   
99999     141                56    244    77    323      31      103   

       허리둘레(cm)  엉덩이둘레(cm)  신장(cm)  체중(kg)  BMI(kg/m^2)  
결측값                                                      
66666         0          0       0       0            0  
77777         0          0       0       0            0  
99999       132        139      46      47           51

### 음주

In [33]:
# 음주여부
data['음주여부'].value_counts()

1        5015
3        4446
2         478
99999      61
Name: 음주여부, dtype: int64

In [34]:
data = nanchange('음주여부',1)

음주여부 결측치 대체 최빈값 : 1


In [35]:
data['음주여부'].value_counts()

1    5076
3    4446
2     478
Name: 음주여부, dtype: int64

In [36]:
#총음주기간
data[data['음주여부']==1]['총음주기간'].value_counts()

77777    5015
99999      59
4           1
2           1
Name: 총음주기간, dtype: int64

In [37]:
index_dr1=data[data['음주여부']==1].index
for x in index_dr1:
    data['총음주기간'][x]=77777
data[data['음주여부']==1]['총음주기간'].value_counts()

/var/folders/3r/4hbcmng97wzgph0qydqtq4d00000gn/T/ipykernel_7487/165586161.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['총음주기간'][x]=77777


77777    5076
Name: 총음주기간, dtype: int64

In [38]:
data['총음주기간'].value_counts()

77777    5078
4        2612
3        1170
2         493
1         366
99999     281
Name: 총음주기간, dtype: int64

In [39]:
data=nanchange2('총음주기간',1)

총음주기간 결측치 대체 최빈값 : 4


### 흡연

In [40]:
data['흡연여부'].value_counts()

1        7207
2        1445
3        1280
99999      68
Name: 흡연여부, dtype: int64

In [41]:
index_sm=data[data['흡연여부']==99999].index
data=data.drop(index_sm)
data

대상자ID  성별  만나이  월평균수입  현재결혼상태  고혈압진단여부  고혈압진단나이  당뇨병진단여부  \
0     K_BASE_00001   2   42      5       2        1    77777        1   
1     K_BASE_00002   2   58      1       2        2       50        1   
2     K_BASE_00003   2   60      5       2        2       50        1   
3     K_BASE_00004   2   73      1       5        2       63        1   
4     K_BASE_00005   2   59      2       2        1    77777        1   
...            ...  ..  ...    ...     ...      ...      ...      ...   
9995  K_BASE_09996   1   66      3       2        1    77777        1   
9996  K_BASE_09997   1   58      7       2        2       58        2   
9997  K_BASE_09998   1   57      5       2        1    77777        1   
9998  K_BASE_09999   2   43      7       2        1    77777        1   
9999  K_BASE_10000   2   43      8       2        1    77777        1   

      당뇨병진단나이  고지혈증진단여부  ...  초경만나이   폐경여부  폐경만나이  임신경험여부  첫임신시만나이  허리둘레(cm)  \
0       77777         2  ...  99999      1  77777       2       22        82   
1       77777         1  ...     16      2     55       2       18        89   
2       77777         2  ...     14      2     47       2       27        78   
3       77777         1  ...     16      2     54       2       21        86   
4       77777         1  ...     14      2     50       2       24        86   
...       ...       ...  ...    ...    ...    ...     ...      ...       ...   
9995    77777         1  ...  77777  77777  77777   77777    77777        85   
9996       48         1  ...  77777  77777  77777   77777    77777        92   
9997    77777         1  ...  77777  77777  77777   77777    77777        83   
9998    77777         1  ...     16      1  77777       2       37        81   
9999    77777         1  ...     13      1  77777       2       25        81   

      엉덩이둘레(cm)  신장(cm)  체중(kg)  BMI(kg/m^2)  
0            95     164      64           24  
1            99     156      64           26  
2            90     154      54           23  
3            93     143      55           27  
4            98     150      60           27  
...         ...     ...     ...          ...  
9995         93     162      61           23  
9996        102     168      70           25  
9997         92     168      64           23  
9998         91     162      62           24  
9999         94     148      61           28  

[9932 rows x 32 columns]

In [42]:
index_sm1=data[data['하루흡연량(개비)']==99999].index
data=data.drop(index_sm1)
data.reset_index(drop=True,inplace=True)
data

대상자ID  성별  만나이  월평균수입  현재결혼상태  고혈압진단여부  고혈압진단나이  당뇨병진단여부  \
0     K_BASE_00001   2   42      5       2        1    77777        1   
1     K_BASE_00002   2   58      1       2        2       50        1   
2     K_BASE_00003   2   60      5       2        2       50        1   
3     K_BASE_00004   2   73      1       5        2       63        1   
4     K_BASE_00005   2   59      2       2        1    77777        1   
...            ...  ..  ...    ...     ...      ...      ...      ...   
9819  K_BASE_09996   1   66      3       2        1    77777        1   
9820  K_BASE_09997   1   58      7       2        2       58        2   
9821  K_BASE_09998   1   57      5       2        1    77777        1   
9822  K_BASE_09999   2   43      7       2        1    77777        1   
9823  K_BASE_10000   2   43      8       2        1    77777        1   

      당뇨병진단나이  고지혈증진단여부  ...  초경만나이   폐경여부  폐경만나이  임신경험여부  첫임신시만나이  허리둘레(cm)  \
0       77777         2  ...  99999      1  77777       2       22        82   
1       77777         1  ...     16      2     55       2       18        89   
2       77777         2  ...     14      2     47       2       27        78   
3       77777         1  ...     16      2     54       2       21        86   
4       77777         1  ...     14      2     50       2       24        86   
...       ...       ...  ...    ...    ...    ...     ...      ...       ...   
9819    77777         1  ...  77777  77777  77777   77777    77777        85   
9820       48         1  ...  77777  77777  77777   77777    77777        92   
9821    77777         1  ...  77777  77777  77777   77777    77777        83   
9822    77777         1  ...     16      1  77777       2       37        81   
9823    77777         1  ...     13      1  77777       2       25        81   

      엉덩이둘레(cm)  신장(cm)  체중(kg)  BMI(kg/m^2)  
0            95     164      64           24  
1            99     156      64           26  
2            90     154      54           23  
3            93     143      55           27  
4            98     150      60           27  
...         ...     ...     ...          ...  
9819         93     162      61           23  
9820        102     168      70           25  
9821         92     168      64           23  
9822         91     162      62           24  
9823         94     148      61           28  

[9824 rows x 32 columns]

In [43]:
data[data['총흡연기간(년)']==99999]['흡연여부'].value_counts()

2    31
3    18
Name: 흡연여부, dtype: int64

In [44]:
data=nanchange2('총흡연기간(년)',0)

총흡연기간(년) 결측치 대체 평균값(반올림) : 25


In [45]:
data=nanchange2('간접흡연여부',1)

간접흡연여부 결측치 대체 최빈값 : 1


### 운동

In [46]:
data['규칙적운동여부(몸에땀이날정도)'].value_counts()

1        5070
2        4729
99999      25
Name: 규칙적운동여부(몸에땀이날정도), dtype: int64

In [47]:
data=nanchange3('규칙적운동여부(몸에땀이날정도)',1)

규칙적운동여부(몸에땀이날정도) 결측치 대체 최빈값 : 1


### 임신 

In [48]:
data['성별'].value_counts()

2    6472
1    3352
Name: 성별, dtype: int64

In [49]:
data=data.drop(data[data['초경만나이']==99999].index)
data=data.drop(data[data['폐경여부']==99999].index)
data=data.drop(data[data['폐경만나이']==99999].index)
data=data.drop(data[data['임신경험여부']==99999].index)
data=data.drop(data[data['첫임신시만나이']==99999].index)
data.reset_index(drop=True,inplace=True)

### 신체정보

In [50]:
data=data.drop(data[data['허리둘레(cm)']==99999].index)
data=data.drop(data[data['엉덩이둘레(cm)']==99999].index)
data=data.drop(data[data['신장(cm)']==99999].index)
data=data.drop(data[data['체중(kg)']==99999].index)
data=data.drop(data[data['BMI(kg/m^2)']==99999].index)
data.reset_index(drop=True,inplace=True)

In [51]:
nanlist=nandf(data)
nanlist

Index(['고혈압진단나이', '당뇨병진단나이', '고지혈증진단나이', '총음주기간', '총흡연기간(년)', '하루흡연량(개비)',
       '초경만나이', '폐경여부', '폐경만나이', '임신경험여부', '첫임신시만나이'],
      dtype='object')


고혈압진단나이  당뇨병진단나이  고지혈증진단나이  총음주기간  총흡연기간(년)  하루흡연량(개비)  초경만나이  폐경여부  \
결측값                                                                          
66666        0        0         0      0         0          0      0     0   
77777     7379     8554      8475   4601      6652       6652   3305  3305   
99999        0        0         0      0         0          0      0     0   

       폐경만나이  임신경험여부  첫임신시만나이  
결측값                            
66666      0       0        0  
77777   5682    3305     3480  
99999      0       0        0

In [52]:
data

대상자ID  성별  만나이  월평균수입  현재결혼상태  고혈압진단여부  고혈압진단나이  당뇨병진단여부  \
0     K_BASE_00002   2   58      1       2        2       50        1   
1     K_BASE_00003   2   60      5       2        2       50        1   
2     K_BASE_00004   2   73      1       5        2       63        1   
3     K_BASE_00005   2   59      2       2        1    77777        1   
4     K_BASE_00006   1   54      2       2        2       50        1   
...            ...  ..  ...    ...     ...      ...      ...      ...   
9208  K_BASE_09996   1   66      3       2        1    77777        1   
9209  K_BASE_09997   1   58      7       2        2       58        2   
9210  K_BASE_09998   1   57      5       2        1    77777        1   
9211  K_BASE_09999   2   43      7       2        1    77777        1   
9212  K_BASE_10000   2   43      8       2        1    77777        1   

      당뇨병진단나이  고지혈증진단여부  ...  초경만나이   폐경여부  폐경만나이  임신경험여부  첫임신시만나이  허리둘레(cm)  \
0       77777         1  ...     16      2     55       2       18        89   
1       77777         2  ...     14      2     47       2       27        78   
2       77777         1  ...     16      2     54       2       21        86   
3       77777         1  ...     14      2     50       2       24        86   
4       77777         1  ...  77777  77777  77777   77777    77777        97   
...       ...       ...  ...    ...    ...    ...     ...      ...       ...   
9208    77777         1  ...  77777  77777  77777   77777    77777        85   
9209       48         1  ...  77777  77777  77777   77777    77777        92   
9210    77777         1  ...  77777  77777  77777   77777    77777        83   
9211    77777         1  ...     16      1  77777       2       37        81   
9212    77777         1  ...     13      1  77777       2       25        81   

      엉덩이둘레(cm)  신장(cm)  체중(kg)  BMI(kg/m^2)  
0            99     156      64           26  
1            90     154      54           23  
2            93     143      55           27  
3            98     150      60           27  
4            97     169      81           28  
...         ...     ...     ...          ...  
9208         93     162      61           23  
9209        102     168      70           25  
9210         92     168      64           23  
9211         91     162      62           24  
9212         94     148      61           28  

[9213 rows x 32 columns]

# 최종 정리 및 추출

In [53]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9213 entries, 0 to 9212
Data columns (total 32 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   대상자ID             9213 non-null   object 
 1   성별                9213 non-null   int64  
 2   만나이               9213 non-null   int64  
 3   월평균수입             9213 non-null   int64  
 4   현재결혼상태            9213 non-null   int64  
 5   고혈압진단여부           9213 non-null   int64  
 6   고혈압진단나이           9213 non-null   int64  
 7   당뇨병진단여부           9213 non-null   int64  
 8   당뇨병진단나이           9213 non-null   int64  
 9   고지혈증진단여부          9213 non-null   int64  
 10  고지혈증진단나이          9213 non-null   int64  
 11  아버지고혈압진단여부        9213 non-null   int64  
 12  어머니고혈압진단여부        9213 non-null   int64  
 13  아버지당뇨병진단여부        9213 non-null   int64  
 14  어머니당뇨병진단여부        9213 non-null   int64  
 15  음주여부              9213 non-null   int64  
 16  총음주기간             9213 non-null   int64  


In [54]:
strcol=['대상자ID', '성별', '월평균수입', '현재결혼상태', '고혈압진단여부', '당뇨병진단여부', '고지혈증진단여부',  '아버지고혈압진단여부','어머니고혈압진단여부', '아버지당뇨병진단여부', '어머니당뇨병진단여부', '음주여부', '총음주기간', '흡연여부','간접흡연여부', '규칙적운동여부(몸에땀이날정도)', '폐경여부','임신경험여부']

In [55]:
for x in strcol:
    data[x]=data[x].astype('category')

In [56]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9213 entries, 0 to 9212
Data columns (total 32 columns):
 #   Column            Non-Null Count  Dtype   
---  ------            --------------  -----   
 0   대상자ID             9213 non-null   category
 1   성별                9213 non-null   category
 2   만나이               9213 non-null   int64   
 3   월평균수입             9213 non-null   category
 4   현재결혼상태            9213 non-null   category
 5   고혈압진단여부           9213 non-null   category
 6   고혈압진단나이           9213 non-null   int64   
 7   당뇨병진단여부           9213 non-null   category
 8   당뇨병진단나이           9213 non-null   int64   
 9   고지혈증진단여부          9213 non-null   category
 10  고지혈증진단나이          9213 non-null   int64   
 11  아버지고혈압진단여부        9213 non-null   category
 12  어머니고혈압진단여부        9213 non-null   category
 13  아버지당뇨병진단여부        9213 non-null   category
 14  어머니당뇨병진단여부        9213 non-null   category
 15  음주여부              9213 non-null   category
 16  총음주기간             9213 n

In [59]:
data=data.replace(77777,0)
data.to_csv("data.csv",mode='w',index = False)

In [60]:
data

대상자ID 성별  만나이 월평균수입 현재결혼상태 고혈압진단여부  고혈압진단나이 당뇨병진단여부  당뇨병진단나이  \
0     K_BASE_00002  2   58     1      2       2       50       1        0   
1     K_BASE_00003  2   60     5      2       2       50       1        0   
2     K_BASE_00004  2   73     1      5       2       63       1        0   
3     K_BASE_00005  2   59     2      2       1        0       1        0   
4     K_BASE_00006  1   54     2      2       2       50       1        0   
...            ... ..  ...   ...    ...     ...      ...     ...      ...   
9208  K_BASE_09996  1   66     3      2       1        0       1        0   
9209  K_BASE_09997  1   58     7      2       2       58       2       48   
9210  K_BASE_09998  1   57     5      2       1        0       1        0   
9211  K_BASE_09999  2   43     7      2       1        0       1        0   
9212  K_BASE_10000  2   43     8      2       1        0       1        0   

     고지혈증진단여부  ...  초경만나이 폐경여부 폐경만나이 임신경험여부 첫임신시만나이 허리둘레(cm) 엉덩이둘레(cm) 신장(cm)  \
0           1  ...     16    2    55      2      18       89        99    156   
1           2  ...     14    2    47      2      27       78        90    154   
2           1  ...     16    2    54      2      21       86        93    143   
3           1  ...     14    2    50      2      24       86        98    150   
4           1  ...      0    0     0      0       0       97        97    169   
...       ...  ...    ...  ...   ...    ...     ...      ...       ...    ...   
9208        1  ...      0    0     0      0       0       85        93    162   
9209        1  ...      0    0     0      0       0       92       102    168   
9210        1  ...      0    0     0      0       0       83        92    168   
9211        1  ...     16    1     0      2      37       81        91    162   
9212        1  ...     13    1     0      2      25       81        94    148   

      체중(kg)  BMI(kg/m^2)  
0         64           26  
1         54           23  
2         55           27  
3         60           27  
4         81           28  
...      ...          ...  
9208      61           23  
9209      70           25  
9210      64           23  
9211      62           24  
9212      61           28  

[9213 rows x 32 columns]